### ISSUE TITLE
Console error when using the DRC weapons

### ISSUE THREAD

**Issue by Sinnikul** [Vuthakral/Draconic_Base#13]
Specifically, I get this error:

[ERROR] LuaCmd:1: Tried to use a NULL entity!
  1. EmitSound - [C]:-1
   2. unknown - LuaCmd:1 (x2)

We're using your Halo SWEP pack as well as the Halo Hunter Weapons made by Impulse.

**Comment by Vuthakral** [comment]
Yeah I'm aware of this. It's due to how I'm attempting to approach the distant sounds. I won't bore you or anyone with the technical talk but the tl;dr is that it fails to get the position/entity to play the sound from because of a delay in the command being processed.

I'm still considering alternative ways to do this system.

**Comment by Vuthakral** [comment]
Fixed a few updates ago on Steam Workshop version with the distant sound function rewrite
