### ISSUE TITLE
Conflict with Black Autumn Playermodel selector.

### ISSUE THREAD

**Issue by ScottVordem** [Vuthakral/Draconic_Base#19]
There is some conflict with the hands selector portion of [Black Autumn PM Selector](https://steamcommunity.com/sharedfiles/filedetails/?id=1350278118).

Applying hands from Black Autumn and upon dying, Draconic Base resets the playermodel hands back to the default hands.

This happens every time the player dies and does not happen when Draconic base is disabled completely.

Black Autumn has a feature to force keep the hands, and Draconic still forces them to reset regardless if this setting is enabled or not.

I do have the big red X selected in Draconic Base and the hands still reset.

Note: This only happens when the player dies. Map transitions and starting a new Garry's Mod session are not effected.

------------------------------------------------------

Also, relatively minor issue with the same addon.

With the experimental firstperson option enabled, applying the playermodel from Black Autumn sometimes results in a distorted body.

Pressing apply in the playermodel selector in draconic base resolves this issue.

**Comment by Vuthakral** [comment]
For the part about c_arms, that's fair and I probably should have thought ahead about that. Will be fixed.

As for the issue with experimental first person, this is caused because the model of the first person body gets changed, but the bone indexes do not due to an engine limitation which results in the jank stuff you see. This only isn't a problem on the Draconic Base's playermodel selector because it internally calls a command which force-removes the model, making the base recreate it. If you want this resolved, you'll need to get in contact with the author of that addon and (politely) ask them to add this to their apply button's functionality: `if Draconic then RunConsoleCommand("drc_refreshcsents") end`

**Comment by Vuthakral** [comment]
Fixed with latest update
