### ISSUE TITLE
[Enhancement] CalcView Priority System for Experimental Firstperson.

### ISSUE THREAD

**Issue by ScottVordem** [Vuthakral/Draconic_Base#21]
There is an addon called [CalcView Priority System](https://steamcommunity.com/sharedfiles/filedetails/?id=2922515253) and it is a developer resource to make custom views not interfere with each other. You can find more information on the addon page itself.

I don't know how it works since I am not a developer, but thought I would make you aware of it in hopes it could be used to enhanced the firstperson view.

In EFP's current state, I have not come across too many issues related to interference of another CalcView, so if you do decide to use it, don't forget to set it as a required item on the Steam workshop page.

**Comment by Vuthakral** [comment]
![image](https://user-images.githubusercontent.com/4466200/215539416-44b3b005-bf4e-40ee-99d3-d3a0719cdea1.png)

edit: to expand on this further since just closing this is kinda scummy, CalcView priority is a bandaid solution to mod authors making CalcView hooks that are intrusive on others, and enables aggressive code styles that are counterproductive. I can keep working the way I do without issue, and add support where needed. The only way problems can occur is special cases or the rare instance where someone else makes code that explicitly goes out of its way to break someone else's CalcView modification.

**Comment by ScottVordem** [comment]
Understood. I am not a developer or coder so I was not sure how useful this is if it even works.

Thanks for clarifying.
